# Generated by Xlator | 2026-09-09T19:04:52

module "pgi-esr-st" {
  source                  = "git::ssh://git@github.com/telus/tf-module-gcp-cloudsql.git?ref=v1.7.1"
  region                  = var.region
  project_id              = var.project_id
  db_server_name          = var.database_instance_name
  db_name                 = var.database_name
  db_version              = var.database_version
  edition                 = var.database_edition
  deletion_protection     = var.deletion_protection
  instance_tier           = var.database_instance_tier
  disk_type               = "PD_SSD"
  disk_autoresize         = var.disk_autoresize
  disk_autoresize_limit   = var.disk_autoresize_limit
  disk_size               = 30
  maintenance_window_day  = 7
  maintenance_window_hour = 6
  backup_start_time       = "06:00"
  backup_location         = var.region
  private_network         = null
  ipv4_enabled            = true
  ssl_mode                = var.ssl_mode
  availability_type       = var.database_availability
  database_flags          = lookup(var.database_instance_flags, "pg-esr-flags")
  deletion_policy         = "ABANDON"
  psc_config = {
    "enabled"                   = true
    "allowed_consumer_projects" = var.allowed_consumer_projects
    "psc_auto_connections" = [
    {
      "consumer_network"            = var.consumer_network,
      "consumer_service_project_id" = var.project_id
    }
    ]
  }
}