# Generated by Xlator — IAM bindings for pgi-esr-st

resource "google_project_iam_member" "telus-dba-gidc-compute" {
  project = var.project_id
  role    = "roles/cloudsql.client"
  member  = "serviceAccount:${var.database_migration_serviceaccount}"
}

resource "google_sql_user" "pgi-esr-st-iam-users" {
  for_each                = var.env == "np" ? var.cloud_sql_iam_users : {}
  project                 = var.project_id
  name                    = each.key
  instance                = module.pgi-esr-st.instance_name
  type                    = each.value
}

resource "google_sql_user" "pgi-esr-st-pr-iam-users" {
  for_each                = var.env == "pr" ? var.cloud_sql_iam_users : {}
  project                 = var.project_id
  name                    = each.key
  instance                = var.database_instance_name
  type                    = each.value
}

resource "google_project_iam_member" "cloudsql_studio_user" {
  project = var.project_id
  role    = "roles/cloudsql.studioUser"
  member  = "group:dldbmigrationgcp@telus.com"
}

resource "google_project_iam_member" "cloudsql_roles" {
  for_each = toset([
    "roles/cloudsql.client",
    "roles/cloudsql.instanceUser",
    "roles/cloudsql.viewer",
  ])
  project = var.project_id
  role    = each.value
  member  = "group:dl_clouddba@telus.com"
}